config/routes.rb
Rails.application.routes.draw do
  get 'rejestracja/strona_domowa'

  devise_for :uzytkowniks
  
  root "rejestracja#strona_domowa"

end

app/models/uzytkownik.rb
class Uzytkownik < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rejestracja_controller.rb
class RejestracjaController < ApplicationController
  def strona_domowa
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rejestracja_helper.rb
module RejestracjaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseAuthentication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/rejestracja/strona_domowa.html.erb
<% if current_uzytkownik %>
     Welcome <%= current_uzytkownik.email %>
     <%= link_to "Sign out", destroy_uzytkownik_session_path, method: :delete %>
<% else %>
     <%= link_to "Sign in", new_uzytkownik_session_path %>
     <%= link_to "Register",new_uzytkownik_registration_path %>
<% end %>